### ISSUE TITLE
Error in detail function

### ISSUE THREAD

**Issue by tcardy** [ckatzorke/howlongtobeat#52]
when using the detail function with a known good id in version 1.7.0

TypeError: Cannot read property 'children' of undefined
    at Function.parseDetails (*******\node_modules\howlongtobeat\dist\main\howlongtobeat.js:111:43)
    at HowLongToBeatService.<anonymous> (*******\node_modules\howlongtobeat\dist\main\howlongtobeat.js:26:45)
    at Generator.next (<anonymous>)
    at fulfilled (*******\node_modules\howlongtobeat\dist\main\howlongtobeat.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by marcelodive** [comment]
Yep, it is happening to me too

**Comment by thulin82** [comment]
Check out @ckatzorke comment in the last post of:
https://github.com/ckatzorke/howlongtobeat/issues/40
